### ISSUE TITLE
Creating many issues quickly triggers spam logic on github.com

### ISSUE THREAD

**Issue by LegalizeAdulthood** [mendhak/Codeplex-Issues-Importer#95]
```
Traceback (most recent call last):
  File "codepleximport.py", line 269, in <module>
    newIssue = gh.create_issue(GITHUB_USERNAME,GITHUB_PROJECT,wi.heading,wi.description,labels=[GITHUB_ISSUELABEL])
  File "build\bdist.win32\egg\github3\decorators.py", line 37, in auth_wrapper
  File "build\bdist.win32\egg\github3\github.py", line 261, in create_issue
  File "build\bdist.win32\egg\github3\decorators.py", line 37, in auth_wrapper
  File "build\bdist.win32\egg\github3\repos\repo.py", line 814, in create_issue
  File "build\bdist.win32\egg\github3\models.py", line 153, in _json
  File "build\bdist.win32\egg\github3\models.py", line 174, in _boolean
github3.exceptions.ForbiddenError: 403 You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.
```

I think the solution is to introduce a delay after creating each issue.

**Comment by varhub** [comment]
see https://developer.github.com/v3/#abuse-rate-limits and octokit/octokit.net#638 and https://github.com/stephencelis/ghi/issues/212
and if you wish... blame it  ;)

**Comment by LegalizeAdulthood** [comment]
I hacked my local copy of the script to insert a 1s delay after creating each issue and then it proceeded through all the issues without triggering this error.

I think the github policy is reasonable, but this script needs to be updated in order to avoid running afoul of the policy.

**Comment by varhub** [comment]
Hello @LegalizeAdulthood, I made another approach. Tell me if it works.
If codeplex uses auth token, delete it and create another. This will bypass the api limit and let you to work  almost in burst mode.

The drawback is that process must handle interruptions and continue (I push issues with a for loop and change the initial value (== issue ID))

**Comment by LegalizeAdulthood** [comment]
Like I said, I already worked around it.
